language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.5.2
# command to install dependencies
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install Django==$DJANGO_VERSION --use-mirrors
# command to run tests
script:
    python pi_time/manage.py test --no-input
