language: python
python:
    - "2.7"
install:
    - pip install setuptools --upgrade --use-mirrors
    - pip install -r requirements.txt 
script:
    - python pi_time/manage.py validate
    - python pi_time/manage.py test pi_time 
