language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt --use-mirrors
script:
    - python pi_time/manage.py validate
    - python pi_time/manage.py test pi_time 
    - python pi_time/manage.py test laptimer 
